import React from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { colors } from "@/components/theme";

const days=[['L','8'],['M','9'],['X','10'],['J','11'],['V','12'],['S','13'],['D','14']];
const appts=[['09:00','Revisión general','Completada','#d7f6e8','#159665'],['09:30','Electrocardiograma','En curso','#d8f5f5','#159c9c'],['10:00','Consulta inicial','En sala de espera','#fff0d8','#f59e0b'],['10:30','Seguimiento','Cancelada','#ffc7c7','#ff6b6b'],['11:00','Chequeo rutinario','Pendiente','#dceeff','#3699ff'],['11:30','Segunda opinión','Pendiente','#dceeff','#3699ff']];
export default function Agenda(){return <View style={styles.screen}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.header}><Text style={styles.headerTitle}>Agenda medica</Text></View><View style={styles.days}>{days.map((d,i)=><TouchableOpacity key={d[1]} style={[styles.day,i===2&&styles.dayActive]}><Text style={[styles.dayLetter,i===2&&styles.white]}>{d[0]}</Text><Text style={[styles.dayNum,i===2&&styles.white]}>{d[1]}</Text></TouchableOpacity>)}</View><View style={styles.stats}><Stat n="8" l="Total Citas" c="#1976d2"/><Stat n="5" l="Atendidas" c="#20b26b"/><Stat n="3" l="Pendientes" c="#ff9800"/></View><Text style={styles.title}>Agenda del día — Miércoles 10 Jun</Text><View style={styles.list}>{appts.map((a)=><View key={a[0]} style={styles.row}><Text style={styles.time}>{a[0]}</Text><View style={styles.card}><View style={{flex:1}}><Text style={styles.cardTitle}>Hola</Text><Text style={styles.cardSub}>{a[1]}</Text></View><View style={[styles.badge,{backgroundColor:a[3]}]}><Text style={[styles.badgeText,{color:a[4]}]}>{a[2]}</Text></View></View></View>)}</View></ScrollView></View>}
function Stat({n,l,c}:{n:string;l:string;c:string}){return <View style={styles.stat}><Text style={[styles.statN,{color:c}]}>{n}</Text><Text style={styles.statL}>{l}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#fbfdfd'},scroll:{paddingBottom:120,backgroundColor:'#fbfdfd'},header:{height:130,backgroundColor:colors.teal,alignItems:'center',justifyContent:'center'},headerTitle:{color:'white',fontSize:30,fontWeight:'900'},days:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:22,marginTop:32},day:{width:52,height:76,borderRadius:22,backgroundColor:'white',alignItems:'center',justifyContent:'center'},dayActive:{backgroundColor:colors.teal},dayLetter:{fontSize:19,color:'#61656d',fontWeight:'800'},dayNum:{fontSize:26,color:colors.text,fontWeight:'900',marginTop:10},white:{color:'white'},stats:{flexDirection:'row',gap:20,paddingHorizontal:22,marginTop:36},stat:{flex:1,height:110,backgroundColor:'white',borderRadius:20,alignItems:'center',justifyContent:'center'},statN:{fontSize:38,fontWeight:'900'},statL:{fontSize:16,color:colors.muted,marginTop:10},title:{fontSize:23,color:colors.text,fontWeight:'900',marginTop:38,marginBottom:24,paddingHorizontal:24},list:{paddingHorizontal:24},row:{flexDirection:'row',marginBottom:26},time:{width:82,fontSize:23,fontWeight:'900',color:colors.text,marginTop:28},card:{flex:1,minHeight:112,backgroundColor:'white',borderRadius:24,paddingHorizontal:22,paddingVertical:22,flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},cardTitle:{fontSize:23,fontWeight:'900',color:colors.text},cardSub:{fontSize:18,color:colors.muted,marginTop:14},badge:{paddingHorizontal:14,height:38,borderRadius:20,alignItems:'center',justifyContent:'center',marginTop:4},badgeText:{fontSize:14,fontWeight:'900'}})
